# Question 14-Final Exam

## Load Libraries

In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

## Load Obesity Dataset from Kaggle and Review

In [39]:
Obesity_CSV = "ObesityDataSet_raw_and_data_sinthetic.csv"
df = pd.read_csv(Obesity_CSV)

In [40]:
df.head(10)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,29.0,Male,1.62,53.0,Sometimes,yes,2.0,3.0,no,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,23.0,Female,1.50,55.0,Sometimes,yes,3.0,3.0,no,no,2.0,yes,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,22.0,Male,1.64,53.0,Sometimes,no,2.0,3.0,no,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,24.0,Male,1.78,64.0,Frequently,yes,3.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
9,22.0,Male,1.72,68.0,no,yes,2.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

## Select Chosen Features

In [46]:
Features = ['Height', 'Age', 'Gender', 'Weight', 'SMOKE']
Features_subset = df[Features].dropna()

Encoded_subset = Features_subset.copy()
ENC_gender = LabelEncoder()
ENC_smoke = LabelEncoder()

Encoded_subset['Gender'] = ENC_gender.fit_transform(Encoded_subset['Gender'])
Encoded_subset['SMOKE'] = ENC_smoke.fit_transform(Encoded_subset['SMOKE'])

Encoded_subset.head(10)

   Height   Age  Gender  Weight  SMOKE
0    1.62  21.0       0    64.0      0
1    1.52  21.0       0    56.0      1
2    1.80  23.0       1    77.0      0
3    1.80  27.0       1    87.0      0
4    1.78  22.0       1    89.8      0
5    1.62  29.0       1    53.0      0
6    1.50  23.0       0    55.0      0
7    1.64  22.0       1    53.0      0
8    1.78  24.0       1    64.0      0
9    1.72  22.0       1    68.0      0

In [42]:
x = Encoded_subset[['Height', 'Age', 'Gender', 'SMOKE']]
y = Encoded_subset['Weight']

## Split Data (30% Test with 70% Train)

In [43]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

## Train the Model

In [44]:
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

LinearRegression()

## Test Set Prediction and Mean Square Error Generation

In [45]:
y_pred = lr_model.predict(x_test)

Mean_Square = mean_squared_error(y_test, y_pred)
print(round(Mean_Square, 3))

498.655